version: "3.9"

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq

    hostname: rabbitmq

    ports:
      - "5672:5672"
      - "15672:15672"

    environment:
      RABBITMQ_DEFAULT_USER: rabbituser
      RABBITMQ_DEFAULT_PASS: rabbit1234

  #######################################
  ## CONFIG SERVER
  #######################################

  configsvr:
    image: mongo:7

    container_name: configsvr

    command: >
      mongod
      --configsvr
      --replSet configReplSet
      --port 27019
      --bind_ip_all

    ports:
      - "27019:27019"

    volumes:
      - config_data:/data/configdb

  #######################################
  ## SHARD 1
  #######################################

  shard1:
    image: mongo:7

    container_name: shard1

    command: >
      mongod
      --shardsvr
      --replSet shard1ReplSet
      --port 27018
      --bind_ip_all

    ports:
      - "27018:27018"

    volumes:
      - shard1_data:/data/db

  #######################################
  ## SHARD 2
  #######################################

  shard2:
    image: mongo:7

    container_name: shard2

    command: >
      mongod
      --shardsvr
      --replSet shard2ReplSet
      --port 27018
      --bind_ip_all

    ports:
      - "27020:27018"

    volumes:
      - shard2_data:/data/db

  #######################################
  ## MONGOS ROUTER
  #######################################

  mongos:
    image: mongo:7

    container_name: mongos

    command: >
      mongos
      --configdb configReplSet/configsvr:27019
      --bind_ip_all

    ports:
      - "27017:27017"

    depends_on:
      - configsvr
      - shard1
      - shard2

  #######################################
  ## GATEWAY
  #######################################

  gateway:
    build: ./gateway

    container_name: gateway

    ports:
      - "8000:8000"

    depends_on:
      - rabbitmq
      - mongos

  #######################################
  ## WORKERS
  #######################################

  worker1:

    build: ./worker

    container_name: worker1

    depends_on:
      - rabbitmq
      - mongos

  worker2:

    build: ./worker

    container_name: worker2

    depends_on:
      - rabbitmq
      - mongos

  worker3:

    build: ./worker

    container_name: worker3

    depends_on:
      - rabbitmq
      - mongos

volumes:
  config_data:
  shard1_data:
  shard2_data:
