version: "3.8"

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq

    environment:
      RABBITMQ_DEFAULT_USER: rabbituser
      RABBITMQ_DEFAULT_PASS: rabbit1234

    ports:
      - "5672:5672"
      - "15672:15672"

  mongodb:
    image: mongo:7
    container_name: mongodb
    hostname: mongodb

    ports:
      - "27017:27017"

    restart: unless-stopped

  gateway:
    build: ./gateway
    container_name: gateway

    depends_on:
      - rabbitmq

    ports:
      - "8000:8000"

    restart: unless-stopped

  worker:
    build: ./worker
    container_name: worker

    depends_on:
      - rabbitmq

    restart: unless-stopped
